server.port=8084
spring.mongodb.uri=mongodb://fare_admin:6cgEvwEBBL8GUfLz@ac-qirhdtw-shard-00-00.zkowzlm.mongodb.net:27017,ac-qirhdtw-shard-00-01.zkowzlm.mongodb.net:27017,ac-qirhdtw-shard-00-02.zkowzlm.mongodb.net:27017/fare_payment_db?ssl=true&replicaSet=atlas-gdihsa-shard-0&authSource=admin&appName=Cluster0
spring.mongodb.database=fare_payment_db